web:
 image: nginx:latest
 ports:
  - "80:80"
 volumes:
  - .:/var/www/html
  - ./site.conf:/etc/nginx/conf.d/000_site.conf
  - ./nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/logs:/var/log/nginx

 links:
  - php

php:
  image: php7_2:latest
  volumes:
   - .:/var/www/html



