web:
 image: nginx:latest
 ports:
  - "80:80"
 volumes:
  - /var/www/gabinet:/var/www/html
  - /var/www/gabinet/site.conf:/etc/nginx/conf.d/000_site.conf
  - /var/www/gabinet/nginx.conf:/etc/nginx/nginx.conf
  - /var/www/gabinet/nginx/logs:/var/log/nginx

 links:
  - php

php:
  image: php7_2:latest
  volumes:
   - /var/www/gabinet:/var/www/html



