web:
 image: nginx:latest
 ports:
  - "8080:80"
 volumes:
  - /var/www/gabinet:/var/www/html
  - /var/www/gabinet/site.conf:/etc/nginx/conf.d/000_site.conf
 links:
  - php

php:
  image: php7_2:latest
  volumes:
   - /var/www/gabinet:/var/www/html



